################################################################################
# VC707 Constraints File
# Sorted (except for FMC, fuck FMC) and human readable
# Author: Mitchell Gu
################################################################################

################################################################################
# CLOCKS
################################################################################

# SYSCLK 200MHz
set_property PACKAGE_PIN E19 [get_ports clk_in1_p]
set_property IOSTANDARD LVDS [get_ports clk_in1_p]
set_property PACKAGE_PIN E18 [get_ports clk_in1_n]
set_property IOSTANDARD LVDS [get_ports clk_in1_n]

################################################################################
# MISC
################################################################################

# CPU Reset (Switch 8)
set_property PACKAGE_PIN AV40 [get_ports i_reset]
set_property IOSTANDARD LVCMOS18 [get_ports i_reset]


################################################################################
# GPIO
################################################################################


# # DIP Switches
# set_property PACKAGE_PIN AV30 [get_ports GPIO_DIP_SW0]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW0]
# set_property PACKAGE_PIN AY33 [get_ports GPIO_DIP_SW1]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW1]
# set_property PACKAGE_PIN BA31 [get_ports GPIO_DIP_SW2]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW2]
# set_property PACKAGE_PIN BA32 [get_ports GPIO_DIP_SW3]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW3]
# set_property PACKAGE_PIN AW30 [get_ports GPIO_DIP_SW4]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW4]
# set_property PACKAGE_PIN AY30 [get_ports GPIO_DIP_SW5]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW5]
# set_property PACKAGE_PIN BA30 [get_ports GPIO_DIP_SW6]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW6]
# set_property PACKAGE_PIN BB31 [get_ports GPIO_DIP_SW7]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_DIP_SW7]

# # Pushbuttons
# set_property PACKAGE_PIN AV39 [get_ports GPIO_SW_C]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_C]
# set_property PACKAGE_PIN AR40 [get_ports GPIO_SW_N]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_N]
# set_property PACKAGE_PIN AU38 [get_ports GPIO_SW_E]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_E]
# set_property PACKAGE_PIN AP40 [get_ports GPIO_SW_S]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_S]
# set_property PACKAGE_PIN AW40 [get_ports GPIO_SW_W]
# set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_W]


################################################################################
# USB-UART Bridge (Silicon Labs CP2103GM)
################################################################################

set_property PACKAGE_PIN AU36 [get_ports i_usart_rx]
set_property IOSTANDARD LVCMOS18 [get_ports i_usart_rx]
# set_property PACKAGE_PIN AT32 [get_ports USB_UART_RTS]
# set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_RTS]
set_property PACKAGE_PIN AU33 [get_ports o_usart_tx]
set_property IOSTANDARD LVCMOS18 [get_ports o_usart_tx]
# set_property PACKAGE_PIN AR34 [get_ports USB_UART_CTS]
# set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_CTS]


################################################################################
# 10/100/1000 Ethernet PHY
################################################################################

# set_property PACKAGE_PIN AK33 [get_ports PHY_MDIO_LS]
# set_property IOSTANDARD LVCMOS18 [get_ports PHY_MDIO_LS]
# set_property PACKAGE_PIN AH31 [get_ports PHY_MDC_LS]
# set_property IOSTANDARD LVCMOS18 [get_ports PHY_MDC_LS]
# set_property PACKAGE_PIN AL31 [get_ports PHY_INT_LS]
# set_property IOSTANDARD LVCMOS18 [get_ports PHY_INT_LS]
# set_property PACKAGE_PIN AJ33 [get_ports PHY_RESET_LS]
# set_property IOSTANDARD LVCMOS18 [get_ports PHY_RESET_LS]
set_property PACKAGE_PIN AH8 [get_ports gtrefclk_p]
set_property PACKAGE_PIN AH7 [get_ports gtrefclk_n]
set_property PACKAGE_PIN AN2 [get_ports txp]
set_property PACKAGE_PIN AM8 [get_ports rxp]
set_property PACKAGE_PIN AN1 [get_ports txn]
set_property PACKAGE_PIN AM7 [get_ports rxn]

################################################################################
# DDR3 SODIMM
################################################################################

set_property PACKAGE_PIN A20    [get_ports DDR3_0_addr[0]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[0]]
set_property PACKAGE_PIN B19    [get_ports DDR3_0_addr[1]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[1]]
set_property PACKAGE_PIN C20    [get_ports DDR3_0_addr[2]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[2]]
set_property PACKAGE_PIN A19    [get_ports DDR3_0_addr[3]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[3]]
set_property PACKAGE_PIN A17    [get_ports DDR3_0_addr[4]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[4]]
set_property PACKAGE_PIN A16    [get_ports DDR3_0_addr[5]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[5]]
set_property PACKAGE_PIN D20    [get_ports DDR3_0_addr[6]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[6]]
set_property PACKAGE_PIN C18    [get_ports DDR3_0_addr[7]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[7]]
set_property PACKAGE_PIN D17    [get_ports DDR3_0_addr[8]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[8]]
set_property PACKAGE_PIN C19    [get_ports DDR3_0_addr[9]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[9]]
set_property PACKAGE_PIN B21    [get_ports DDR3_0_addr[10]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[10]]
set_property PACKAGE_PIN B17    [get_ports DDR3_0_addr[11]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[11]]
set_property PACKAGE_PIN A15    [get_ports DDR3_0_addr[12]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[12]]
set_property PACKAGE_PIN A21    [get_ports DDR3_0_addr[13]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[13]]
set_property PACKAGE_PIN F17    [get_ports DDR3_0_addr[14]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[14]]
set_property PACKAGE_PIN E17    [get_ports DDR3_0_addr[15]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_addr[15]]

set_property PACKAGE_PIN D21    [get_ports DDR3_0_ba[0]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_ba[0]]
set_property PACKAGE_PIN C21    [get_ports DDR3_0_ba[1]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_ba[1]]
set_property PACKAGE_PIN D18    [get_ports DDR3_0_ba[2]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_ba[2]]

set_property PACKAGE_PIN N14    [get_ports DDR3_0_dq[0]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[0]]
set_property PACKAGE_PIN N13    [get_ports DDR3_0_dq[1]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[1]]
set_property PACKAGE_PIN L14    [get_ports DDR3_0_dq[2]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[2]]
set_property PACKAGE_PIN M14    [get_ports DDR3_0_dq[3]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[3]]
set_property PACKAGE_PIN M12    [get_ports DDR3_0_dq[4]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[4]]
set_property PACKAGE_PIN N15    [get_ports DDR3_0_dq[5]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[5]]
set_property PACKAGE_PIN M11    [get_ports DDR3_0_dq[6]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[6]]
set_property PACKAGE_PIN L12    [get_ports DDR3_0_dq[7]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[7]]
set_property PACKAGE_PIN K14    [get_ports DDR3_0_dq[8]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[8]]
set_property PACKAGE_PIN K13    [get_ports DDR3_0_dq[9]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[9]]
set_property PACKAGE_PIN H13    [get_ports DDR3_0_dq[10]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[10]]
set_property PACKAGE_PIN J13    [get_ports DDR3_0_dq[11]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[11]]
set_property PACKAGE_PIN L16    [get_ports DDR3_0_dq[12]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[12]]
set_property PACKAGE_PIN L15    [get_ports DDR3_0_dq[13]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[13]]
set_property PACKAGE_PIN H14    [get_ports DDR3_0_dq[14]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[14]]
set_property PACKAGE_PIN J15    [get_ports DDR3_0_dq[15]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[15]]
set_property PACKAGE_PIN E15    [get_ports DDR3_0_dq[16]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[16]]
set_property PACKAGE_PIN E13    [get_ports DDR3_0_dq[17]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[17]]
set_property PACKAGE_PIN F15    [get_ports DDR3_0_dq[18]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[18]]
set_property PACKAGE_PIN E14    [get_ports DDR3_0_dq[19]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[19]]
set_property PACKAGE_PIN G13    [get_ports DDR3_0_dq[20]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[20]]
set_property PACKAGE_PIN G12    [get_ports DDR3_0_dq[21]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[21]]
set_property PACKAGE_PIN F14    [get_ports DDR3_0_dq[22]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[22]]
set_property PACKAGE_PIN G14    [get_ports DDR3_0_dq[23]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[23]]
set_property PACKAGE_PIN B14    [get_ports DDR3_0_dq[24]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[24]]
set_property PACKAGE_PIN C13    [get_ports DDR3_0_dq[25]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[25]]
set_property PACKAGE_PIN B16    [get_ports DDR3_0_dq[26]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[26]]
set_property PACKAGE_PIN D15    [get_ports DDR3_0_dq[27]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[27]]
set_property PACKAGE_PIN D13    [get_ports DDR3_0_dq[28]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[28]]
set_property PACKAGE_PIN E12    [get_ports DDR3_0_dq[29]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[29]]
set_property PACKAGE_PIN C16    [get_ports DDR3_0_dq[30]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[30]]
set_property PACKAGE_PIN D16    [get_ports DDR3_0_dq[31]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[31]]
set_property PACKAGE_PIN A24    [get_ports DDR3_0_dq[32]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[32]]
set_property PACKAGE_PIN B23    [get_ports DDR3_0_dq[33]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[33]]
set_property PACKAGE_PIN B27    [get_ports DDR3_0_dq[34]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[34]]
set_property PACKAGE_PIN B26    [get_ports DDR3_0_dq[35]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[35]]
set_property PACKAGE_PIN A22    [get_ports DDR3_0_dq[36]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[36]]
set_property PACKAGE_PIN B22    [get_ports DDR3_0_dq[37]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[37]]
set_property PACKAGE_PIN A25    [get_ports DDR3_0_dq[38]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[38]]
set_property PACKAGE_PIN C24    [get_ports DDR3_0_dq[39]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[39]]
set_property PACKAGE_PIN E24    [get_ports DDR3_0_dq[40]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[40]]
set_property PACKAGE_PIN D23    [get_ports DDR3_0_dq[41]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[41]]
set_property PACKAGE_PIN D26    [get_ports DDR3_0_dq[42]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[42]]
set_property PACKAGE_PIN C25    [get_ports DDR3_0_dq[43]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[43]]
set_property PACKAGE_PIN E23    [get_ports DDR3_0_dq[44]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[44]]
set_property PACKAGE_PIN D22    [get_ports DDR3_0_dq[45]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[45]]
set_property PACKAGE_PIN F22    [get_ports DDR3_0_dq[46]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[46]]
set_property PACKAGE_PIN E22    [get_ports DDR3_0_dq[47]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[47]]
set_property PACKAGE_PIN A30    [get_ports DDR3_0_dq[48]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[48]]
set_property PACKAGE_PIN D27    [get_ports DDR3_0_dq[49]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[49]]
set_property PACKAGE_PIN A29    [get_ports DDR3_0_dq[50]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[50]]
set_property PACKAGE_PIN C28    [get_ports DDR3_0_dq[51]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[51]]
set_property PACKAGE_PIN D28    [get_ports DDR3_0_dq[52]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[52]]
set_property PACKAGE_PIN B31    [get_ports DDR3_0_dq[53]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[53]]
set_property PACKAGE_PIN A31    [get_ports DDR3_0_dq[54]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[54]]
set_property PACKAGE_PIN A32    [get_ports DDR3_0_dq[55]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[55]]
set_property PACKAGE_PIN E30    [get_ports DDR3_0_dq[56]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[56]]
set_property PACKAGE_PIN F29    [get_ports DDR3_0_dq[57]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[57]]
set_property PACKAGE_PIN F30    [get_ports DDR3_0_dq[58]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[58]]
set_property PACKAGE_PIN F27    [get_ports DDR3_0_dq[59]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[59]]
set_property PACKAGE_PIN C30    [get_ports DDR3_0_dq[60]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[60]]
set_property PACKAGE_PIN E29    [get_ports DDR3_0_dq[61]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[61]]
set_property PACKAGE_PIN F26    [get_ports DDR3_0_dq[62]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[62]]
set_property PACKAGE_PIN D30    [get_ports DDR3_0_dq[63]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dq[63]]

set_property PACKAGE_PIN M13    [get_ports DDR3_0_dm[0]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[0]]
set_property PACKAGE_PIN K15    [get_ports DDR3_0_dm[1]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[1]]
set_property PACKAGE_PIN F12    [get_ports DDR3_0_dm[2]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[2]]
set_property PACKAGE_PIN A14    [get_ports DDR3_0_dm[3]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[3]]
set_property PACKAGE_PIN C23    [get_ports DDR3_0_dm[4]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[4]]
set_property PACKAGE_PIN D25    [get_ports DDR3_0_dm[5]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[5]]
set_property PACKAGE_PIN C31    [get_ports DDR3_0_dm[6]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[6]]
set_property PACKAGE_PIN F31    [get_ports DDR3_0_dm[7]]
set_property IOSTANDARD SSTL15  [get_ports DDR3_0_dm[7]]

set_property PACKAGE_PIN N16        [get_ports DDR3_0_dqs_p[0]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_p[0]]
set_property PACKAGE_PIN M16        [get_ports DDR3_0_dqs_n[0]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_n[0]]
set_property PACKAGE_PIN K12        [get_ports DDR3_0_dqs_p[1]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_p[1]]
set_property PACKAGE_PIN J12        [get_ports DDR3_0_dqs_n[1]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_n[1]]
set_property PACKAGE_PIN H16        [get_ports DDR3_0_dqs_p[2]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_p[2]]
set_property PACKAGE_PIN G16        [get_ports DDR3_0_dqs_n[2]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_n[2]]
set_property PACKAGE_PIN C15        [get_ports DDR3_0_dqs_p[3]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_p[3]]
set_property PACKAGE_PIN C14        [get_ports DDR3_0_dqs_n[3]]
set_property IOSTANDARD SSTL15      [get_ports DDR3_0_dqs_n[3]]
set_property PACKAGE_PIN A26        [get_ports DDR3_0_dqs_p[4]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_p[4]]
set_property PACKAGE_PIN A27        [get_ports DDR3_0_dqs_n[4]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_n[4]]
set_property PACKAGE_PIN F25        [get_ports DDR3_0_dqs_p[5]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_p[5]]
set_property PACKAGE_PIN E25        [get_ports DDR3_0_dqs_n[5]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_n[5]]
set_property PACKAGE_PIN B28        [get_ports DDR3_0_dqs_p[6]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_p[6]]
set_property PACKAGE_PIN B29        [get_ports DDR3_0_dqs_n[6]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_n[6]]
set_property PACKAGE_PIN E27        [get_ports DDR3_0_dqs_p[7]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_p[7]]
set_property PACKAGE_PIN E28        [get_ports DDR3_0_dqs_n[7]]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_dqs_n[7]]

set_property PACKAGE_PIN H20 [get_ports DDR3_0_odt]
set_property IOSTANDARD SSTL15 [get_ports DDR3_0_odt]

# set_property PACKAGE_PIN H18 [get_ports DDR3_ODT1]
# set_property IOSTANDARD SSTL15 [get_ports DDR3_ODT1]
set_property PACKAGE_PIN C29 [get_ports DDR3_0_reset_n]
set_property IOSTANDARD LVCMOS15 [get_ports DDR3_0_reset_n]

set_property PACKAGE_PIN J17 [get_ports DDR3_0_cs_n]
set_property IOSTANDARD SSTL15 [get_ports DDR3_0_cs_n]

# set_property PACKAGE_PIN J20 [get_ports DDR3_S1_B]
# set_property IOSTANDARD SSTL15 [get_ports DDR3_S1_B]
# set_property PACKAGE_PIN G17 [get_ports DDR3_TEMP_EVENT]
# set_property IOSTANDARD SSTL15 [get_ports DDR3_TEMP_EVENT]
set_property PACKAGE_PIN F20 [get_ports DDR3_0_we_n]
set_property IOSTANDARD SSTL15 [get_ports DDR3_0_we_n]

set_property PACKAGE_PIN K17 [get_ports DDR3_0_cas_n]
set_property IOSTANDARD SSTL15 [get_ports DDR3_0_cas_n]
set_property PACKAGE_PIN E20 [get_ports DDR3_0_ras_n]
set_property IOSTANDARD SSTL15 [get_ports DDR3_0_ras_n]

set_property PACKAGE_PIN K19 [get_ports DDR3_0_cke]
set_property IOSTANDARD SSTL15 [get_ports DDR3_0_cke]

# set_property PACKAGE_PIN J18 [get_ports DDR3_CKE1]
# set_property IOSTANDARD SSTL15 [get_ports DDR3_CKE1]

set_property PACKAGE_PIN H19 [get_ports DDR3_0_ck_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_ck_p]
set_property PACKAGE_PIN G18 [get_ports DDR3_0_ck_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_0_ck_n]

# set_property PACKAGE_PIN G19 [get_ports DDR3_CLK1_P]
# set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_CLK1_P]
# set_property PACKAGE_PIN F19 [get_ports DDR3_CLK1_N]
# set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR3_CLK1_N]

# # IDK what this is
# set_property PACKAGE_PIN M17 [get_ports 10N483]
# set_property IOSTANDARD SSTL15 [get_ports 10N483]
# set_property PACKAGE_PIN L17 [get_ports 10N484]
# set_property IOSTANDARD SSTL15 [get_ports 10N484]
# set_property PACKAGE_PIN N19 [get_ports 10N485]
# set_property IOSTANDARD SSTL15 [get_ports 10N485]
# set_property PACKAGE_PIN N18 [get_ports 10N486]
# set_property IOSTANDARD SSTL15 [get_ports 10N486]
# set_property PACKAGE_PIN M19 [get_ports 10N487]
# set_property IOSTANDARD SSTL15 [get_ports 10N487]
# set_property PACKAGE_PIN M18 [get_ports 10N488]
# set_property IOSTANDARD SSTL15 [get_ports 10N488]
# set_property PACKAGE_PIN P20 [get_ports 10N489]
# set_property IOSTANDARD SSTL15 [get_ports 10N489]
# set_property PACKAGE_PIN N20 [get_ports 10N490]
# set_property IOSTANDARD SSTL15 [get_ports 10N490]
# set_property PACKAGE_PIN L20 [get_ports 10N491]
# set_property IOSTANDARD SSTL15 [get_ports 10N491]
# set_property PACKAGE_PIN L19 [get_ports 10N492]
# set_property IOSTANDARD SSTL15 [get_ports 10N492]

# # External 0.75V Reference
# set_property PACKAGE_PIN B18 [get_ports VTTVREF]
# set_property IOSTANDARD SSTL15 [get_ports VTTVREF]

# # Some DCI VRP/N resistor connection?
# set_property PACKAGE_PIN J11 [get_ports VRP_39]
# set_property IOSTANDARD SSTL15 [get_ports VRP_39]

##################################################################
# Auto Generate 4 pair J by contraint_gen.py 

# set_property PACKAGE_PIN P42 [get_ports I_LAST_SCK]
# set_property IOSTANDARD LVCMOS18 [get_ports I_LAST_SCK]
set_property PACKAGE_PIN B33 [get_ports IO_Dat[72]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[72]]
set_property PACKAGE_PIN K32 [get_ports IO_Dat[73]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[73]]
set_property PACKAGE_PIN Y30 [get_ports IO_Dat[74]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[74]]
set_property PACKAGE_PIN A37 [get_ports IO_Dat[75]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[75]]
set_property PACKAGE_PIN M39 [get_ports IO_Dat[80]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[80]]
set_property PACKAGE_PIN N40 [get_ports IO_Dat[82]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[82]]
set_property PACKAGE_PIN J28 [get_ports IO_Dat[88]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[88]]
set_property PACKAGE_PIN G29 [get_ports IO_Dat[90]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[90]]
set_property PACKAGE_PIN R28 [get_ports IO_Dat[94]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[94]]
set_property PACKAGE_PIN M32 [get_ports IO_Dat[100]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[100]]
set_property PACKAGE_PIN K27 [get_ports IO_Dat[102]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[102]]
set_property PACKAGE_PIN J31 [get_ports IO_Dat[106]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[106]]
set_property PACKAGE_PIN H25 [get_ports IO_Dat[108]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[108]]
set_property PACKAGE_PIN T29 [get_ports IO_Dat[114]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[114]]
set_property PACKAGE_PIN L25 [get_ports IO_Dat[116]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[116]]
set_property PACKAGE_PIN N25 [get_ports IO_Dat[120]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[120]]
set_property PACKAGE_PIN U31 [get_ports IO_Dat[124]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[124]]
set_property PACKAGE_PIN R42 [get_ports I_StartPulse]
set_property IOSTANDARD LVCMOS18 [get_ports I_StartPulse]
set_property PACKAGE_PIN R40 [get_ports I_BypAsysnFIFO]
set_property IOSTANDARD LVCMOS18 [get_ports I_BypAsysnFIFO]
set_property PACKAGE_PIN H39 [get_ports IO_DatVld]
set_property IOSTANDARD LVCMOS18 [get_ports IO_DatVld]
set_property PACKAGE_PIN B32 [get_ports IO_Dat[71]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[71]]
set_property PACKAGE_PIN L31 [get_ports IO_Dat[70]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[70]]
set_property PACKAGE_PIN Y29 [get_ports IO_Dat[69]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[69]]
set_property PACKAGE_PIN B36 [get_ports IO_Dat[66]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[66]]
set_property PACKAGE_PIN N38 [get_ports IO_Dat[81]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[81]]
set_property PACKAGE_PIN N39 [get_ports IO_Dat[83]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[83]]
set_property PACKAGE_PIN K28 [get_ports IO_Dat[89]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[89]]
set_property PACKAGE_PIN G28 [get_ports IO_Dat[93]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[93]]
set_property PACKAGE_PIN P28 [get_ports IO_Dat[95]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[95]]
set_property PACKAGE_PIN L32 [get_ports IO_Dat[101]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[101]]
set_property PACKAGE_PIN J27 [get_ports IO_Dat[105]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[105]]
set_property PACKAGE_PIN H31 [get_ports IO_Dat[107]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[107]]
set_property PACKAGE_PIN H26 [get_ports IO_Dat[113]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[113]]
set_property PACKAGE_PIN T30 [get_ports IO_Dat[115]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[115]]
set_property PACKAGE_PIN L26 [get_ports IO_Dat[119]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[119]]
set_property PACKAGE_PIN N26 [get_ports IO_Dat[121]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[121]]
set_property PACKAGE_PIN T31 [get_ports IO_Dat[125]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[125]]
set_property PACKAGE_PIN F32 [get_ports IO_Dat[64]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[64]]
set_property PACKAGE_PIN F35 [get_ports IO_Dat[57]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[57]]
set_property PACKAGE_PIN M38 [get_ports IO_Dat[53]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[53]]
set_property PACKAGE_PIN B38 [get_ports IO_Dat[63]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[63]]
set_property PACKAGE_PIN D32 [get_ports IO_Dat[68]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[68]]
set_property PACKAGE_PIN J42 [get_ports IO_Dat[76]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[76]]
set_property PACKAGE_PIN C34 [get_ports IO_Dat[78]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[78]]
set_property PACKAGE_PIN K38 [get_ports IO_Dat[84]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[84]]
set_property PACKAGE_PIN A39 [get_ports IO_Dat[86]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[86]]
set_property PACKAGE_PIN A34 [get_ports IO_Dat[92]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[92]]
set_property PACKAGE_PIN N31 [get_ports IO_Dat[97]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[97]]
set_property PACKAGE_PIN G24 [get_ports IO_Dat[99]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[99]]
set_property PACKAGE_PIN H30 [get_ports IO_Dat[104]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[104]]
set_property PACKAGE_PIN K30 [get_ports IO_Dat[110]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[110]]
set_property PACKAGE_PIN H23 [get_ports IO_Dat[112]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[112]]
set_property PACKAGE_PIN P25 [get_ports IO_Dat[118]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[118]]
set_property PACKAGE_PIN K24 [get_ports IO_Dat[122]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[122]]
set_property PACKAGE_PIN M28 [get_ports IO_Dat[126]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[126]]
set_property PACKAGE_PIN P22 [get_portsOI_DatRdy]
set_property IOSTANDARD LVCMOS18 [get_ports OI_DatRdy]
set_property PACKAGE_PIN P21 [get_ports O_CmdVld]
set_property IOSTANDARD LVCMOS18 [get_ports O_CmdVld]
set_property PACKAGE_PIN G32 [get_ports IO_Dat[59]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[59]]
set_property PACKAGE_PIN F34 [get_ports IO_Dat[60]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[60]]
set_property PACKAGE_PIN M37 [get_ports IO_Dat[58]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[58]]
set_property PACKAGE_PIN B37 [get_ports IO_Dat[54]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[54]]
set_property PACKAGE_PIN E32 [get_ports IO_Dat[67]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[67]]
set_property PACKAGE_PIN K42 [get_ports IO_Dat[77]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[77]]
set_property PACKAGE_PIN C33 [get_ports IO_Dat[79]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[79]]
set_property PACKAGE_PIN K37 [get_ports IO_Dat[85]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[85]]
set_property PACKAGE_PIN B39 [get_ports IO_Dat[87]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[87]]
set_property PACKAGE_PIN B34 [get_ports IO_Dat[91]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[91]]
set_property PACKAGE_PIN P30 [get_ports IO_Dat[96]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[96]]
set_property PACKAGE_PIN H24 [get_ports IO_Dat[98]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[98]]
set_property PACKAGE_PIN J30 [get_ports IO_Dat[103]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[103]]
set_property PACKAGE_PIN K29 [get_ports IO_Dat[109]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[109]]
set_property PACKAGE_PIN G23 [get_ports IO_Dat[111]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[111]]
set_property PACKAGE_PIN P26 [get_ports IO_Dat[117]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[117]]
set_property PACKAGE_PIN K25 [get_ports IO_Dat[123]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[123]]
set_property PACKAGE_PIN M29 [get_ports IO_Dat[127]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[127]]
# set_property PACKAGE_PIN P23 [get_ports I_Monitor_Out[3]]
# set_property IOSTANDARD LVCMOS18 [get_ports I_Monitor_Out[3]]
# set_property PACKAGE_PIN N21 [get_ports I_Monitor_OutVld]
# set_property IOSTANDARD LVCMOS18 [get_ports I_Monitor_OutVld]
set_property PACKAGE_PIN E35 [get_ports IO_Dat[52]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[52]]
set_property PACKAGE_PIN J41 [get_ports IO_Dat[55]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[55]]
set_property PACKAGE_PIN H36 [get_ports IO_Dat[61]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[61]]
set_property PACKAGE_PIN L41 [get_ports IO_Dat[50]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[50]]
set_property PACKAGE_PIN E33 [get_ports IO_Dat[41]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[41]]
set_property PACKAGE_PIN C38 [get_ports IO_Dat[40]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[40]]
set_property PACKAGE_PIN H40 [get_ports IO_Dat[47]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[47]]
set_property PACKAGE_PIN H38 [get_ports IO_Dat[45]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[45]]
set_property PACKAGE_PIN E37 [get_ports IO_Dat[43]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[43]]
set_property PACKAGE_PIN F40 [get_ports IO_Dat[24]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[24]]
set_property PACKAGE_PIN D37 [get_ports IO_Dat[18]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[18]]
set_property PACKAGE_PIN F36 [get_ports IO_Dat[12]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[12]]
set_property PACKAGE_PIN W30 [get_ports IO_Dat[8]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[8]]
set_property PACKAGE_PIN J25 [get_ports IO_Dat[6]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[6]]
set_property PACKAGE_PIN G26 [get_ports IO_Dat[1]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[1]]
# set_property PACKAGE_PIN R30 [get_ports O_SW_clk]
# set_property IOSTANDARD LVCMOS18 [get_ports O_SW_clk]
set_property PACKAGE_PIN L22 [get_ports O_DatOE]
set_property IOSTANDARD LVCMOS18 [get_ports O_DatOE]
# set_property PACKAGE_PIN L21 [get_ports O_SW0]
# set_property IOSTANDARD LVCMOS18 [get_ports O_SW0]
set_property PACKAGE_PIN L24 [get_ports I_SysRst_n]
set_property IOSTANDARD LVCMOS18 [get_ports I_SysRst_n]
set_property PACKAGE_PIN U29 [get_ports I_SysClk]
set_property IOSTANDARD LVCMOS18 [get_ports I_SysClk]
set_property PACKAGE_PIN E34 [get_ports IO_Dat[51]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[51]]
set_property PACKAGE_PIN J40 [get_ports IO_Dat[56]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[56]]
set_property PACKAGE_PIN J36 [get_ports IO_Dat[62]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[62]]
set_property PACKAGE_PIN M41 [get_ports IO_Dat[65]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[65]]
set_property PACKAGE_PIN D33 [get_ports IO_Dat[49]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[49]]
set_property PACKAGE_PIN C39 [get_ports IO_Dat[42]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[42]]
set_property PACKAGE_PIN H41 [get_ports IO_Dat[48]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[48]]
set_property PACKAGE_PIN G38 [get_ports IO_Dat[46]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[46]]
set_property PACKAGE_PIN E38 [get_ports IO_Dat[44]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[44]]
set_property PACKAGE_PIN F41 [get_ports IO_Dat[23]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[23]]
set_property PACKAGE_PIN D38 [get_ports IO_Dat[19]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[19]]
set_property PACKAGE_PIN F37 [get_ports IO_Dat[13]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[13]]
set_property PACKAGE_PIN W31 [get_ports IO_Dat[7]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[7]]
set_property PACKAGE_PIN J26 [get_ports IO_Dat[5]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[5]]
set_property PACKAGE_PIN G27 [get_ports IO_Dat[0]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[0]]
# set_property PACKAGE_PIN P31 [get_ports O_spi_cs_n]
# set_property IOSTANDARD LVCMOS18 [get_ports O_spi_cs_n]
# set_property PACKAGE_PIN M22 [get_ports I_config_req]
# set_property IOSTANDARD LVCMOS18 [get_ports I_config_req]
# set_property PACKAGE_PIN M21 [get_ports O_SW1]
# set_property IOSTANDARD LVCMOS18 [get_ports O_SW1]
# set_property PACKAGE_PIN M24 [get_ports I_DLL_lock]
# set_property IOSTANDARD LVCMOS18 [get_ports I_DLL_lock]
# set_property PACKAGE_PIN V29 [get_ports O_bypass]
# set_property IOSTANDARD LVCMOS18 [get_ports O_bypass]
set_property PACKAGE_PIN D36 [get_ports IO_Dat[26]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[26]]
set_property PACKAGE_PIN K40 [get_ports IO_Dat[34]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[34]]
set_property PACKAGE_PIN L42 [get_ports IO_Dat[31]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[31]]
set_property PACKAGE_PIN G33 [get_ports IO_Dat[38]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[38]]
set_property PACKAGE_PIN N41 [get_ports IO_Dat[36]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[36]]
set_property PACKAGE_PIN G37 [get_ports IO_Dat[32]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[32]]
set_property PACKAGE_PIN J38 [get_ports IO_Dat[28]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[28]]
set_property PACKAGE_PIN G42 [get_ports IO_Dat[22]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[22]]
set_property PACKAGE_PIN C36 [get_ports IO_Dat[20]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[20]]
set_property PACKAGE_PIN E39 [get_ports IO_Dat[16]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[16]]
set_property PACKAGE_PIN L37 [get_ports IO_Dat[14]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[14]]
set_property PACKAGE_PIN A36 [get_ports IO_Dat[10]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[10]]
set_property PACKAGE_PIN H29 [get_ports IO_Dat[4]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[4]]
set_property PACKAGE_PIN N29 [get_ports IO_Dat[2]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[2]]
set_property PACKAGE_PIN D35 [get_ports IO_Dat[39]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[39]]
set_property PACKAGE_PIN K39 [get_ports IO_Dat[30]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[30]]
set_property PACKAGE_PIN M42 [get_ports IO_Dat[33]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[33]]
set_property PACKAGE_PIN H33 [get_ports IO_Dat[25]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[25]]
set_property PACKAGE_PIN P41 [get_ports IO_Dat[37]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[37]]
set_property PACKAGE_PIN G36 [get_ports IO_Dat[35]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[35]]
set_property PACKAGE_PIN J37 [get_ports IO_Dat[29]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[29]]
set_property PACKAGE_PIN G41 [get_ports IO_Dat[27]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[27]]
set_property PACKAGE_PIN C35 [get_ports IO_Dat[21]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[21]]
set_property PACKAGE_PIN F39 [get_ports IO_Dat[17]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[17]]
set_property PACKAGE_PIN M36 [get_ports IO_Dat[15]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[15]]
set_property PACKAGE_PIN A35 [get_ports IO_Dat[11]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[11]]
set_property PACKAGE_PIN H28 [get_ports IO_Dat[9]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[9]]
set_property PACKAGE_PIN N28 [get_ports IO_Dat[3]]
set_property IOSTANDARD LVCMOS18 [get_ports IO_Dat[3]]

